baseURL = 'https://simonshine.dk/'
languageCode = 'en-us'
title = 'Simon Shine'
theme = 'retro'

[taxonomies]
tag = "tags"

[pagination]
pagerSize = 500

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# m10c parameters

[[menu.main]]
  name = "Index"
  url = "/"
  weight = 10

[[menu.main]]
  # identifier = ""
  name = "Links"
  url = "/links/"
  weight = 20

[[menu.main]]
  # identifier = ""
  name = "About"
  url = "/about/"
  weight = 30

[[menu.main]]
  name = "Contact"
  url = "/contact/"
  weight = 35

[[menu.main]]
  # identifier = ""
  name = "datamatik.blog"
  url = "https://simonshine.dk/tags/datamatik/"
  weight = 40

[params]
  author = 'Simon Shine'
  description = "a personal website"
  avatar = '/img/sshine-triangles.png'
  menu_item_separator = ' &middot; '

[[params.social]]
  icon = "brand-github"
  name = "GitHub"
  url = "https://github.com/sshine"

# [[params.social]]
#   icon = "brand-iterm2"
#   name = "Computer Science Blog"
#   url = "https://datamatik.blog"

# [[params.social]]
#   icon = "brand-devdotto"
#   name = "dev.to blog"
#   url = "https://dev.to/sshine"

[[params.social]]
  icon = "brand-nixos"
  name = "nix.tools"
  url = "https://discourse.nixos.org/u/sshine/summary"

[[params.social]]
  icon = "brand-linkedin"
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/simon-shine-66b667268/"

[[params.social]]
  icon = "brand-stackoverflow"
  name = "StackOverflow"
  url = "https://stackoverflow.com/users/235908/sshine"

[[params.social]]
  icon = "rss"
  name = "RSS"
  url = "/index.xml"
